### ISSUE TITLE
How to cover code for weather.js or Text.js which are not exported

### ISSUE THREAD

**Issue by chaurasiagovind** [adobe/aem-sample-we-retail-journal#11]
I tried writing test cases for Other files in the repository, getting below warning/error.

_

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

_ 

An example would be helpful.

**Comment by pfauchere** [comment]
> You likely forgot to export your component from the file it's defined

You may have forgotten to export the component you are trying to instantiate in another file

`export class MyCalss`

or

`export MapTo('resource/type')(MyClass)`

**Comment by chaurasiagovind** [comment]
Yes, you are right. I was just wondering If there is some way to test them without exporting, as the  other components(e.g. Text js) in the example repo were not having the classes exported.
