### ISSUE TITLE
Upgrade to Angular 7+

### ISSUE THREAD

**Issue by YoannBureau** [adobe/aem-sample-we-retail-journal#26]
Hi,

I've succefully upgraded the angular app to version 7.1.3.
I want to create a PR for that, but it seems I need rights on the repo for that.

Are you interested in this PR?

**Comment by pfauchere** [comment]
Hi Yoann,

Yes, we are interested in your contribution. Could you please submit it via a fork of the project?

**Comment by YoannBureau** [comment]
Sure, just submited the PR: https://github.com/adobe/aem-sample-we-retail-journal/pull/28

**Comment by YoannBureau** [comment]
so?

**Comment by lydiapuric** [comment]
Thanks, we will have a look at it as soon as possible.

**Comment by samuelmeuli** [comment]
The [AEM Project Archetype](https://github.com/adobe/aem-project-archetype) can now generate Angular 8 projects. Please use that project as a reference.
