### ISSUE TITLE
Dependency on event-stream@3.3.6

### ISSUE THREAD

**Issue by amair** [adobe/aem-sample-we-retail-journal#31]
There is a dependency on Event-stream 3.3.6, but this has removed from NPM because some malicious code which attempts to steal cryptocurrency wallets have been injected.

https://github.com/dominictarr/event-stream/issues/116#issuecomment-441759047

Workaround is to downgrade the dependency in package-lock.json to 3.3.4

**Comment by norbiorb** [comment]
I think this was yet solved in PR https://github.com/adobe/aem-sample-we-retail-journal/pull/19 by upgrading nodemon to version 1.18.7

**Comment by lydiapuric** [comment]
@norbiorb is right. Which version of the sample are you working on? There was a new release last week.

**Comment by lydiapuric** [comment]
@amair Looking at https://www.npmjs.com/package/psl this relies on event-stream and the issue regarding event-stream 3.3.6 got addressed with https://github.com/wrangr/psl/issues/39.
We are currently using `v1.1.29` and fix is in `v1.1.31`. I will create a PR for this.

**Comment by lydiapuric** [comment]
Dependencies psl is implicite in 
- npm@6.4.1, latest version is 6.5.0 which relies on 
- request@2.88.0,  which is the latest version.

psl@1.1.29 has a dependency on event-stream@3.3.4:
There is no reference anymore in our package.json files to event-stream 3.3.6, so there is nothing we can do from our side here.

react-app@1.1.1
└─┬ request@2.88.0
  └─┬ tough-cookie@2.4.3
    └── psl@1.1.29 

angular-app@1.1.1
├─┬ npm@6.4.1
│ └─┬ request@2.88.0
│   └─┬ tough-cookie@2.4.3
│     └── psl@1.1.29 
└─┬ request@2.88.0
  └─┬ tough-cookie@2.4.3
    └── psl@1.1.29

**Comment by lydiapuric** [comment]
Resolving as fixed.
