### ISSUE TITLE
OSGi dependency failure com.adobe.cq.export.json.hierarchy,version=[1.0,2)    

### ISSUE THREAD

**Issue by josephh** [adobe/aem-sample-we-retail-journal#36]
AEM 6.4 with SP2.
Cloned the project and checked out development branch.

Ran mvn clean install -P autoInstallPackage.

`We.Retail Journal Corecom.adobe.cq.sample.spa.we-retail-journal-core` and `We.Retail Journal Server Side Rendering com.adobe.cq.sample.spa.we-retail-journal-ssr` bundles show as installed but not active.  

We retail journal core shows imported packages resolution problem, `com.adobe.cq.export.json.hierarchy,version=[1.0,2) -- Cannot be resolved`.

**Comment by josephh** [comment]
https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/issues/45 suggests installing 6.4. SP3 to solve this problem.  Same problem persists for me with SP3.  Is there an AEM version + service pack known to work with this project?  (Or is the issue somewhere else?)

**Comment by lydiapuric** [comment]
I cannot reproduce this issue with an AEM 6.4. SP3. The bundles are active, no dependency issues.
I installed the whole application with "mvn -PautoInstallSinglePackage". 
Installing the core bundle only with "mvn clean install -PautoInstallPackage" works also for me as expected.
@josephh  Can you please confirm you installed the complete application first with "mvn -PautoInstallSinglePackage"?

**Comment by josephh** [comment]
@davidjgonzalez's suggested use of a different jar file (com.adobe.cq.export.json/0.1.7-CQ-4226752-B006/) [here](https://github.com/Adobe-Marketing-Cloud/aem-guides/issues/17) solved the osgi package import problem for me.  And i see in the we-journal-retail-core pom in this project there is a todo comment left inline beside the  `<!-- TODO: CQ-4243301 remove after the backport of the API and its inclusion in the Uber-Jar  -->` com.adobe.cq.export.json artifact entry.

**Comment by josephh** [comment]
Thanks @lydiapuric I didn't use the autoInstallSinglePackage profile - just the autoInstallPackage one.

**Comment by lydiapuric** [comment]
@josephh Could you please try to install it once with the autoInstallSinglePackage profile? This is the recommended way proposed.
It shouldn't be necessary to upload a different jar file.
Regarding the TODO: This issue is still in the backlog.

**Comment by josephh** [comment]
Hi @lydiapuric 
Whether i use the ...singlePackage maven profile or the ...Package one, the project still deploys the osgi bundle com.adobe.cq.export.json - as specified in the project.  The meta for this osgi bundle shows the package export as 'com.adobe.cq.export.json,version=2.0.1' but not the required 'com.adobe.cq.export.json.hierarchy'.  
If i install the jar suggested by @davidjgonzalez, then the com.adobe.cq.export.json shows its package exports as 
```
Exported Packages | com.adobe.cq.export.json,version=2.0.1com.adobe.cq.export.json.hierarchy,version=1.0.0com.adobe.cq.export.json.hierarchy.type,version=1.0.0
-- | --
```
...and now i can succesfully click 'activate' on the we retail journal bundles.

Or have i misunderstood the problem?

**Comment by lydiapuric** [comment]
Can you please explain step by step how you installed your application? Strange thing is that I cannot reproduce this issue.

**Comment by josephh** [comment]
Hi @lydiapuric I will add a note here to say what i did.  In your environment, which osgi bundle jar (and at which version?) satisfies the import of com.adobe.cq.export.json.hierarchy from the com.adobe.cq.sample.spa.we-retail-journal-core 1.1.9.SNAPSHOT bundle?

I did the following, 
unpack and run aem 6.4
installed service pack 6.4.2 from package share
cloned this project
git checkout development
mvn clean install -P autoInstallPackage

**Comment by josephh** [comment]
Although my local aem instance now renders http://localhost:4502/editor.html/content/we-retail-journal/react/en/home.html ok in authoring mode, I can't seem to edit it and we retail journal packages in crx/packmgr show a dependency problem, 

Dependencies: | day/cq60/product:cq-ui-wcm-editor-content:(1.0.138,)

😒

**Comment by lydiapuric** [comment]
I did the following: No dependency problems, editing works:
- unpack and run AEM 6.4

- install service pack 6.4.3 from package share on top of 6.4
I have installed service pack 6.4.3 on top of a 6.4.2. Note: Unfortunately there is currently a known issue with 6.4.3 on top on 6.4.2 that editing does not work, reinstall package 'cq-ui-wcm-admin-content-1.0.1004.zip' fixes this

- git checkout latest version of sample spa development branch
- mvn -PautoInstallSinglePackage
- Access http://localhost:4502/editor.html/content/we-retail-journal/angular/en/home.html (non SSR)

**Comment by josephh** [comment]
Thanks @lydiapuric I will roll back to 6.4 with no service packs and try putting 6.4.3 straight on...
but i'm confused about the cq-ui-wcm-admin-content-1.0.1004.  The sample journal code complains in crx/packmgr about the version i mention above (*not* 1.0.1004)
```"Refusing to install package adobe/aem640/sample:we-retail-journal-content:1.1.9-SNAPSHOT. required dependencies missing: [day/cq60/product:cq-ui-wcm-editor-content:(1.0.138,)]"``` (even though that package appears to be installed, according to my local package manager)

**Comment by josephh** [comment]
issue seems to be:

1. aem 6.4 comes with com.adobe.cq.export.json 0.1.2, with its osgi meta declaring `Exported Packages | com.adobe.cq.export.json,version=2.0.1` (but not com.adobe.cq.export.json.hierarchy).
2. sp2 doesn't update to com.adobe.cq.export.json, so any bundle - including we retail journal core -  consuming com.adobe.cq.export.json.hierarchy fails to resolve. 
3. sp3 installs an updated com.adobe.cq.export.json bundle v0.1.10 - as seen following install in crx/de (/libs/system/aem-service-pkg-6.4.3/install/com.adobe.cq.export.json-0.1.10.jar).  This bundle declares package export com.adobe.cq.export.json.hierarchy, so the journal sample osgi code resolves ok.

@lydiapuric thanks for your help today.  I can't see how the development branch of the journal sample code can work without com.adobe.cq.export.json bundle v0.1.10, i.e. service pack 3 - unless it is installed separately.  I don't know why installing SP3 on top of SP2 doesn't work (won't this cause operational difficulties to AEM hosting that needs to deploy these SPs in series in production systems?), or why the content package `day/cq60/product:cq-ui-wcm-editor-content:(1.0.138,)` is flagged as problematic with sp2?  Any insights much appreciated. 

 Editing in authoring mode didn't work for me because I had 'disable cache' ticked in chrome browser tools 😞

**Comment by pfauchere** [comment]
We faced issues with SP3 that impacts the update from 6.4.2 to 6.4.3. Please refer to the release notes [0] under the known issues section, issue id: CQ-4260316

[0] https://helpx.adobe.com/experience-manager/6-4/release-notes/sp-release-notes.html
