### ISSUE TITLE
Unable to edit components after copy-paste within layout container

### ISSUE THREAD

**Issue by ghost** [adobe/aem-sample-we-retail-journal#37]
Steps to reproduce:

1. Set up an instance of AEM 6.4 with Service Pack 3 and We.Retail Journal installed.
2. Navigate to<host>:<port>/editor.html/content/we-retail-journal/react/en/home.html
3. Make a copy of any component and paste it within the container. Do not reload the page.

Expected behavior:
newly created component appears with authoring controls.

Actual behavior:
newly created component appears without any ability to toggle controls.

**Comment by pfauchere** [comment]
Hi,

There is a known issue that may relate to the current issue. Did you apply the SP3 on top of the SP2? If yes, please try applying the SP3 on top of 6.4.0 or 6.4.1 instead.

https://helpx.adobe.com/experience-manager/6-4/release-notes/sp-release-notes.html#KnownIssues

Regards,

**Comment by Vasiliy-Bolgar** [comment]
Hi @pfauchere 
Thank you for your answer.

We've tried to install SP3 on top of pure AEM 6.4 instance. And on top of SP1 and SP2. The issue still reproduces.

I would be pleasant if you share a bit more information.
Is root cause of this behavior in We Retail Journal code or on the AEM SPA Editor side. What's your opinion?
Is there any workaround for that at this time?

Regards,
V.

**Comment by pfauchere** [comment]
Hi,

I confirm the issue you are experiencing. It most probably relates to an issue between the editor and the SPA SDK. I'll create a ticket and we'll prioritize a fix. In the meantime, you may have to avoid using the copy-paste functionality or can refresh the page to have the new component instance authorable. Thank you very much for reporting the problem

Regards,

**Comment by pfauchere** [comment]
Resolved on the editor side. 6.5 includes the fix. 6.4 will be updated via SP

Ref id: CQ-4262640

**Comment by Vasiliy-Bolgar** [comment]
@pfauchere, thanks a lot!
