### ISSUE TITLE
Project doesn't build with Java 11

### ISSUE THREAD

**Issue by keepthebyte** [adobe/aem-sample-we-retail-journal#40]
Looks like same as https://github.com/adobe/aem-core-wcm-components/issues/491 

[ERROR] Errors: 
[ERROR]   PageImplTest.testConfigChildPage:213 » NoClassDefFound javax/annotation/PostCo...
[ERROR]   PageImplTest.testRequestFilteredNestedChildPages:235 » NoClassDefFound javax/a...

**Comment by pfauchere** [comment]
Merged into development branch
