### ISSUE TITLE
not able to edit the template and set policy

### ISSUE THREAD

**Issue by cqsapient** [adobe/aem-sample-we-retail-journal#48]
I am following this hello world tutorial 
https://helpx.adobe.com/experience-manager/kt/sites/using/spa-editor-helloworld-tutorial-use.html#putting-together

but I am not able to edit the policy as specified in step 4- 

> Select the main Layout Container and select the Policy icon to open its policy:

> After saving, you should see the HelloWorld component as an allowed component in the Layout Container.

It is mentioned int he tutorial that - 

> In the latest version of the SPA Editor, Editable templates can be used in the same way as with traditional Sites implementations. This will be revisited later with our custom component.

Also mentioned in the wknd SPA editor tutorial https://helpx.adobe.com/au/experience-manager/kt/sites/using/getting-started-spa-wknd-tutorial-develop/react/chapter-0.html 

that 

> With the initial release of the SPA Editor the UI for Editable Templates cannot be used. This is expected to be updated in the next release of the SPA Editor.

I am on AEM 6.4.4(service pack 4) on AEM 6.4 beta jar 

![image](https://user-images.githubusercontent.com/22097490/57437603-745d5000-7285-11e9-88f5-40f94c9cb454.png)

but still not able to edit the template to set its policy.

Is this expected behaviour?

Should I edit the editable template for SPA by manually making changes in crx-de as described in 

https://helpx.adobe.com/au/experience-manager/kt/sites/using/getting-started-spa-wknd-tutorial-develop/react/chapter-0.html 

> In order to update features of the template, developers will need to do this manually via CRXDE-Lite or in the XML in the ui.content project.  

request you to please let me know. Will appreciate it. Thanks.

**Comment by godanny86** [comment]
hi @cqsapient I will update the docs referenced to be more clear. Basically, Template Editor works with the SPA Editor in 6.5 but does not work in 6.4. I believe there are plans to backport this functionality to 6.4, but I'm not sure. @pfauchere can you confirm?

**Comment by pfauchere** [comment]
Sorry to keep you waiting. The backport to 6.4.5 has been dropped. 6.5.0 already contains the support for the editable templates and will get access to the SSR OSGi OOTB services via 6.5.1.

We would like to gather customer data and use-cases before investing the time to backport both the editable template support of the SSR features to 6.4.

Thank you for understanding,

cc @gabrielwalt

**Comment by pfauchere** [comment]
In an unexpected final plot twist, the template support and SSR features have been added to the incoming 6.4.5 version

**Comment by favvvvvvv** [comment]
Hi @pfauchere, I can't see the template support change you mentioned listed on the [6.4 SP Release Notes page](https://docs.adobe.com/content/help/en/experience-manager-64/release-notes/sp-release-notes.html). Was template support for SPA backported to 6.4.* in the end?
