### ISSUE TITLE
App doesn't work on IE 11

### ISSUE THREAD

**Issue by cqsapient** [adobe/aem-sample-we-retail-journal#52]
We know that react doesn't support IE11 , but I hope AEM SPA developers didn't completely exclude IE11 from it's support matrix.

http://localhost:4502/editor.html/content/we-retail-journal/react/en/home.html

doesn't work with the error - 

SCRIPT438: Object doesn't support property or method 'endsWith'

Adding import 'react-app-polyfill/ie11';
import 'core-js'; in App/index.js also doesn't solve the issue.

Please let us know how to enable SPA app and SPA authoring on IE11

**Comment by jamesg1** [comment]
Was `import 'react-app-polyfill/ie11';` at the top of your js?
Example:
```
// This must be the first line in src/index.js
import 'react-app-polyfill/ie11';
``` 
See https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md IE11 has missing javascript features which require polyfills to port the functionality.

**Comment by samuelmeuli** [comment]
The [AEM Project Archetype](https://github.com/adobe/aem-project-archetype) can now be used to generate SPA projects and includes polyfills for IE11 by default. Please use that project as a reference.
