### ISSUE TITLE
Support AEM 6.2

### ISSUE THREAD

**Issue by QuanTran91** [adobe/aem-sample-we-retail-journal#55]
Is it possible to support AEM 6.2 (6.1, 6.0)? At the moment, I can integrate Angular component using custom component. However, I want not only integrate Angular page but also entire Angular app. I tried to downgrade project to AEM 6.2 but it did not work.

Could you someone help me on this? I would appreciate.

Thanks.

**Comment by gabrielwalt** [comment]
Hi @QuanTran91,

We do not support the SPA Editor on AEM 6.3 or older, sorry about that. Also, 6.2 and previous versions are already beyond the end of core support [1], so there's not much we can do for back-porting anything them anymore. The best would be for you to upgrade, ideally to 6.5, or at least to 6.4.

Best,
Gabriel

[1] https://helpx.adobe.com/support/programs/eol-matrix.html
