### ISSUE TITLE
Vue.js support

### ISSUE THREAD

**Issue by sumerion** [adobe/aem-sample-we-retail-journal#62]
Hi,

Thank you for this cool demo project to show how SPAs can work within AEM.

We at a specilized adobe sites company would like to make it work with vue.js and contribute a 'cq-vue-editable-components'. Plus the integration in the we retail journal demo.

Are you interested in that contribution and can you help us on the way in terms of guidelines?

Many thanks,
Kris.

**Comment by pfauchere** [comment]
Hi,

Thank you very much for the offer. We currently are discussing how we can best support such an initiative. We will come back to you when we have an agreement.

Regards,

Patrick

**Comment by pfauchere** [comment]
Question answered and no new communication on that matter. Closing the issue
