### ISSUE TITLE
MapTo - @adobe/cq-react-editable-components

### ISSUE THREAD

**Issue by smo043** [adobe/aem-sample-we-retail-journal#64]
Hello, 

MapTo HOC wraps an additional 'div' around the component. We have a use case where Carousel is author-able component and card as another author-able component. Because an additional 'div' is wrapped for both of the components, the  layout is breaking. 

Is there a way we can toggle on/off the 'div'?

Below is how the structure looks

`<div><Carousel><div><Card></Card><div></div></div></Carousel><div></div></div>`

**Comment by echart** [comment]
Hi @SMOHA786 , how do you solve this?

**Comment by smo043** [comment]
I wrote a custom wrapper to handle this scenario. I can share it with you incase if you need it.

**Comment by echart** [comment]
Hi again @SMOHA786, thanks for you quickly answer.

Yes, i'm having the same problem with this div wrapper and i would like to check your solution if you could share.

Thank you,

**Comment by smo043** [comment]
Sure will share the github url here

**Comment by echart** [comment]
up just to ensure that you will not forget 😄

**Comment by smo043** [comment]
@echart - Sent you the invitation link, accept it.
