### ISSUE TITLE
apixu weather forecast end point is broken

### ISSUE THREAD

**Issue by anandkilli** [adobe/aem-sample-we-retail-journal#84]
Hello,

The weather forecast call http://api.apixu.com/v1/forecast.json?key=29956e2dd75344d2894215728182003&days=5&q=Basel is failing. Opening it in a new tab reveals the following
{
  "0": "#################################################################################################################################",
  "1": "#                                                                                                                               #",
  "2": "# IMPORTANT - PLEASE UPDATE YOUR API ENDPOINT                                                                                   #",
  "3": "#                                                                                                                               #",
  "4": "# This API endpoint is deprecated and has now been shut down. To keep using the apixu API, please update your integration       #",
  "5": "# to use the new weatherstack API endpoint, designed as a simple drop-in replacement.                                           #",
  "6": "# You will be required to create an account at https://weatherstack.com and obtain an API access key.                           #",
  "7": "#                                                                                                                               #",
  "8": "# For more information on how to upgrade please visit our Github Tutorial at: https://github.com/apilayer/weatherstack#readme   #",
  "9": "#                                                                                                                               #",
  "a": "#################################################################################################################################"
}

**Comment by pfauchere** [comment]
Got rid of the key in the source. From that point on, you will have to provide your own.
