### ISSUE TITLE
PKIX path building failed when using SSR by https

### ISSUE THREAD

**Issue by walesyu** [adobe/aem-sample-we-retail-journal#85]
Hi, 
Everything is fine when I using SSR via http, but when I  use SSR with HTTPS I get an error of SSLHandshakeException:

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

I have tried to install my CER in Truststore via http://localhost:4502/libs/granite/security/content/truststore.html
But the error still occurs.

**Comment by pfauchere** [comment]
By googling a bit, I found [0]. I hope it helps to answer the question. It's more of a generic AEM configuration problem than anything related to SPA or the current project.

[0] https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/adding-self-signed-certificate-into-aem-6-4-trustore/td-p/282752
