### ISSUE TITLE
Meaning of AppPage

### ISSUE THREAD

**Issue by ofirattia** [adobe/aem-sample-we-retail-journal#89]
Hi,

I noticed that in your example, the page will be load only if the AppPage component is loaded within the ImportComponents, why?

https://github.com/adobe/aem-sample-we-retail-journal/blob/master/react-app/src/components/Page.js

**Comment by pfauchere** [comment]
The presence of the ImportComponents.js file is a structural decision taken during the conception of this sample project. Feel free to structure your project at your convenience. In this example, we opted for centralizing the calls to the module loader in one place. BTW, for a more comprehensive example, please refer to [0]. We are keeping the current example public until [0] contains a section related to SSR configuration.

[0] https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events
